### ISSUE TITLE
Agent fails to render jobs with non-ASCII chars in title

### ISSUE THREAD

**Issue by guidow** [pyfarm/pyfarm-agent#289]
When running a job with non-ASCII characters in its title, pyfarm-agent will fail with the following error messages:

    2015-06-03 17:14:35 ERROR    - pf.agent.http.assign - Loading jobtype for assignment 4c43c69a-cfb4-4f2e-9e1e-b2071b15e96f failed, removing.
    2015-06-03 17:14:35 WARNING  - pf.agent.http.assign - Could not process log message Traceback (most recent call last):
    File "/var/tmp/virtualenv/pyfarm-agent-python2/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1201, in mainLoop               
        self.runUntilCurrent()                                                                                                                                                         
    File "/var/tmp/virtualenv/pyfarm-agent-python2/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 797, in runUntilCurrent         
        f(*a, **kw)                                                                                                                                                                    
    File "/var/tmp/virtualenv/pyfarm-agent-python2/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 383, in callback               
        self._startRunCallbacks(result)                                                                                                                                                
    File "/var/tmp/virtualenv/pyfarm-agent-python2/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 491, in _startRunCallbacks     
        self._runCallbacks()                                                                                                                                                           
    --- <exception caught here> ---                                                                                                                                                    
    File "/var/tmp/virtualenv/pyfarm-agent-python2/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 578, in _runCallbacks          
        current.result = callback(current.result, *args, **kw)                                                                                                                         
    File "/home/guido/git/pyfarm/pyfarm-agent/pyfarm/agent/http/api/assign.py", line 345, in loaded_jobtype                                                                          
        instance = jobtype_class(request_data)                                                                                                                                         
    File "/home/guido/git/pyfarm/pyfarm-agent/pyfarm/jobtypes/core/jobtype.py", line 290, in __init__                                                                                
        logger.debug("Instanced %r", self)                                                                                                                                             
    File "/home/guido/git/pyfarm/pyfarm-agent/pyfarm/agent/logger/python.py", line 48, in debug                                                                                      
        time=time(), logLevel=DEBUG)                                                                                                                                                   
    File "/var/tmp/virtualenv/pyfarm-agent-python2/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/threadable.py", line 53, in sync                 
        return function(self, *args, **kwargs)                                                                                                                                         
    File "/var/tmp/virtualenv/pyfarm-agent-python2/lib/python2.7/site-packages/Twisted-15.0.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 203, in msg                        
        self.observers[i](actualEventDict)                                                                                                                                             
    File "/home/guido/git/pyfarm/pyfarm-agent/pyfarm/agent/logger/twistd.py", line 213, in __call__                                                                                  
        self.emit(event)                                                                                                                                                               
    File "/home/guido/git/pyfarm/pyfarm-agent/pyfarm/agent/logger/twistd.py", line 160, in emit                                                                                      
        message = text % args                                                                                                                                                          
    File "/home/guido/git/pyfarm/pyfarm-agent/pyfarm/jobtypes/core/jobtype.py", line 303, in __repr__                                                                                
        str(self.assignment["job"]["title"]))                                                                                                                                          
    exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 15: ordinal not in range(128)                                                              
    with args ()

**Comment by guidow** [comment]
Fixed in #290
